Follow convention, temp variable in lowercase
Signed-off-by: Johan Burati <johan.burati@gmail.com>

diff --git a/reagent/reagent b/reagent/reagent
--- a/reagent/reagent
+++ b/reagent/reagent
@@ -8,16 +8,16 @@
 # public domain.
 shopt -s extglob
 # timeout keys automatically (not compatible with older versions of OpenSSH)
-KEY_TIMEOUT="-t 10h"
+key_timeout="-t 10h"
 
 # TODO portability problems of killall (e.g. Solaris?)
 killall -u `id -un` ssh-agent
 
 ssh-agent -s | grep -v echo > "$HOME/.ssh-agent"
-STATUS=$?
-if [ $STATUS -ne 0 ]; then
-  echo "error: non-zero exit starting ssh-agent: status=$STATUS" >&2
-  exit $STATUS
+status=$?
+if [ $status -ne 0 ]; then
+  echo "error: non-zero exit starting ssh-agent: status=$status" >&2
+  exit $status
 fi
 
 # if have tty, try to read in keys (which could prompt for passwords)
@@ -25,7 +25,7 @@ if test -t 0; then
   . "$HOME/.ssh-agent"
   for private_key in $HOME/.ssh/id_!(*.pub) $HOME/.ssh/identity; do
     if [ -f "$private_key" ]; then
-      ssh-add $KEY_TIMEOUT "$private_key"
+      ssh-add $key_timeout "$private_key"
     fi
   done
 fi
